name: CI build

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
          cache: maven
      - name: prepare CI script flags
        run: chmod +x ./ci.sh
      - name: run CI script
        run: ./ci.sh